#
# config.toml
#

DefaultContentLanguage = "ja"             # ¿¿¿¿¿¿¿¿¿¿¿¿¿¿
languageCode = "ja-JP"                    # ¿¿¿¿¿¿¿¿¿¿¿¿
publishDir = "docs"

baseurl = "https://bobu.github.io/"   # ¿¿¿¿¿¿¿¿¿¿URL
title = "boldering club / ¿¿"
theme = "hugo-phlat-theme"                # ¿¿¿¿¿¿¿¿¿¿¿¿

[permalinks]
post = "/:year/:month/:slug/"           # post ¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿
page = "/:slug/"                        # page ¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿

[taxonomies]
tag = "tags"                            # ¿¿¿¿¿¿¿
category = "categories"                 # ¿¿¿¿¿¿¿¿¿

[params]
keywords = ["programming", "developer"] # ¿¿¿¿¿¿ keywords ¿¿¿¿¿¿¿¿¿¿¿¿¿¿ (meta keywords)
description = "boldaring team blog"           # ¿¿¿¿¿¿ description ¿¿¿¿¿¿¿¿¿¿¿¿¿¿ (meta description)

[[menu.header]]
name = "Home"
weight = 1
url = "/"

[[menu.header]]
name = "About"
weight = 2
url = "/about/"
